name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        uses: cypress-io/github-action@v6
        with:
          runTests: false
      - name: Run Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
        env: 
          IMPORTANT_TOKEN: ${{ secrets.IMPORTANT_TOKEN }}
          CYPRESS_TOKEN: ${{ secrets.CYPRESS_TOKEN }}
