name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        uses: cypress-io/github-action@v6
        with:
          runTests: false
      - name: Run Tests
        uses: cypress-io/github-action@v6
        with:
          install: false